version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    command: bash -lc "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.example
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: ./backend
    command: celery -A ecommerce worker -l info
    env_file:
      - .env.example
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis

  celery_beat:
    build: ./backend
    command: celery -A ecommerce beat -l info
    env_file:
      - .env.example
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis

  frontend:
    build: ./frontend
    command: bash -lc "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend

volumes:
  pgdata:
